### ISSUE TITLE
Feature request: create branch from story

### ISSUE THREAD

**Issue by gunzip** [brayovsky/pivotaly#91]
Thank you for this extension ! The only thing I miss is a way to checkout a new branch from an existing story. This forces me to open pivotal (web) just to grab the story id. That would be nice to have some listing (like the one in "link story") when you open "Git: create new branch..."

**Comment by brayovsky** [comment]
Hey! Thanks for the positive comment. I'm not sure I understand your request. Currently if you perform a git checkout from wherever all current iteration stories will be listed for you to pick the story you prefer to be working on in the new branch.

**Comment by gunzip** [comment]
Sorry I cannot get it (what do you mean exactly with "perform a git checkout from wherever" ?)
I'm used to checkout new branches from vscode nearly-bottom-left branch pointer:

![image](https://user-images.githubusercontent.com/148224/71662656-86c75500-2d52-11ea-8212-2ba13e01d6ba.png)

and I cannot see the list of current iteration stories (which would satisfy the request indeed, as you correctly pointed out)

**Comment by brayovsky** [comment]
I now understand what you mean. Just continue with the process, when vs-code performs the checkout, a list of stories will appear for you to link the new branch. I mean:

```
- Pick +Create new branch from...
- Enter branch name
- Select a ref to create the new branch name from
- VS Code will then perform a checkout to the branch
- Pivotaly will detect the checkout and fetch current iteration stories
for you to link the new branch to a story
```

The downside to this if you **need** to name the branch with the story id you might need to go and  pick the id from pivotal (web) which I suppose is your problem.

It might be impossible to override the choices presented after clicking `+Create new branch from` but it is possible to list the current stories in the side panel for one to copy paste whichever id is needed at any moment. What do you think?

**Comment by gunzip** [comment]
> The downside to this if you need to name the branch with the story id you might need to go and pick the id from pivotal (web) which I suppose is your problem.

exactly ! :) I think that the solution you propose would be just perfect.

**Comment by brayovsky** [comment]
Added backlog and current stories to side panel.
