### ISSUE TITLE
Could not successfully start story without points, Unable to add points from extension

### ISSUE THREAD

**Issue by excenter** [brayovsky/pivotaly#94]
getting `unable to start story #######`
First time using the extension, not sure if it's me or the app, is this expected?

**Comment by excenter** [comment]
Upon further reflection: I was unable to start a ticket that hadn't been estimated. Is it possible to assign points from the extension?

**Comment by brayovsky** [comment]
Thanks for this. It is currently not possible to assign points to a story and impossible to start an unestimated story. I'll mark this as a feature request to estimate a story from the extension.

**Comment by brayovsky** [comment]
- Added estimate story command
- Run estimate story command when an action fails due to estimation and redo the action if estimation is successful
