### ISSUE TITLE
Refresh story list

### ISSUE THREAD

**Issue by swidnikk** [brayovsky/pivotaly#95]
Can't find a way to refresh and pull in new stories.

**Comment by brayovsky** [comment]
Thanks for this. Do you mean a way to pull in new stories that you may want to link a new branch to? Currently the extension does not display stories other than the one you are currently working on.
Everytime you switch a branch, all current stories are pulled and displayed.

**Comment by brayovsky** [comment]
Added current and backlog stories to sidepanel with ability to refresh stories.
