### ISSUE TITLE
Control panel options disappear

### ISSUE THREAD

**Issue by jbarbour3** [brayovsky/pivotaly#97]
to recreate the issues install the extension, pass the pivotal API token, then select (not a pivotal project) from the list of available projects. This makes the control panel options go away. Even after disabling and re-installing the extension the control panel options remain hidden.

**Comment by brayovsky** [comment]
Thanks for this @jbarbour3. I had actually identified this. There is already a fix. Previously when a workspace was marked as `not a pivotal project`, that was final. You would never be able to use Pivotaly in the workspace.
[this](https://github.com/brayovsky/pivotaly/pull/93) enables one to reinstate a workspace with a control panel option to reinstate the workspace appearing.
This is going to be in v0.7.0 in a few days.

**Comment by brayovsky** [comment]
Fixed by #93

**Comment by brayovsky** [comment]
Fixed by #93
